# Seed data for CrediLens - 48 Smartphone products (Apple, Samsung, Realme)
# This file is used to populate the PostgreSQL database on Render

import urllib.parse

def generate_search_links(product_name, company_name):
    """Generate search URLs for product on major e-commerce sites"""
    query = urllib.parse.quote_plus(f"{company_name} {product_name}")
    official_links = {
        'Apple': 'https://www.apple.com/shop/buy-iphone',
        'Samsung': 'https://www.samsung.com/us/mobile/phones/',
        'Realme': 'https://www.realme.com/global/'
    }
    return {
        'link_amazon': f"https://www.amazon.com/s?k={query}",
        'link_flipkart': f"https://www.flipkart.com/search?q={query}",
        'link_official': official_links.get(company_name),
        'link_other': None
    }

SEED_PRODUCTS = [
    {'company_name': 'Apple', 'product_name': 'iPhone X', 'batch_number': 'IMPORT-2017', 'category': 'Smartphone', 'processor_score': 235000, 'ram_gb': 3, 'storage_gb': 64, 'battery_mah': 2716, 'screen_inches': 5.8, 'camera_mp': 12.0, 'price_usd': 999, 'weight_g': 174, 'processor_model': 'Apple A11 Bionic (10nm, 6-core CPU, 3-core GPU)', 'ram_type': '3GB LPDDR4X', 'storage_type': '64GB/256GB NVMe', 'camera_sensor_main': 'Sony IMX315 (12MP, f/1.8, OIS)', 'camera_sensor_ultra': None, 'camera_sensor_telephoto': 'Sony IMX315 (12MP, f/2.4, 2x optical zoom)', 'battery_tech': 'Li-Ion (2716mAh, non-removable)', 'charging_watt': 15, 'display_type': 'Super Retina OLED, HDR10, Dolby Vision', 'refresh_rate_hz': 60},
    {'company_name': 'Apple', 'product_name': 'iPhone 8', 'batch_number': 'IMPORT-2017', 'category': 'Smartphone', 'processor_score': 230000, 'ram_gb': 2, 'storage_gb': 64, 'battery_mah': 1821, 'screen_inches': 4.7, 'camera_mp': 12.0, 'price_usd': 699, 'weight_g': 148, 'processor_model': 'Apple A11 Bionic (10nm, 6-core CPU, 3-core GPU)', 'ram_type': '2GB LPDDR4X', 'storage_type': '64GB/256GB NVMe', 'camera_sensor_main': 'Sony IMX315 (12MP, f/1.8, OIS)', 'camera_sensor_ultra': None, 'camera_sensor_telephoto': None, 'battery_tech': 'Li-Ion (1821mAh, non-removable)', 'charging_watt': 15, 'display_type': 'Retina IPS LCD', 'refresh_rate_hz': 60},
    {'company_name': 'Apple', 'product_name': 'iPhone 8 Plus', 'batch_number': 'IMPORT-2017', 'category': 'Smartphone', 'processor_score': 235000, 'ram_gb': 3, 'storage_gb': 64, 'battery_mah': 2691, 'screen_inches': 5.5, 'camera_mp': 12.0, 'price_usd': 799, 'weight_g': 202, 'processor_model': 'Apple A11 Bionic (10nm, 6-core CPU, 3-core GPU)', 'ram_type': '3GB LPDDR4X', 'storage_type': '64GB/256GB NVMe', 'camera_sensor_main': 'Sony IMX315 (12MP, f/1.8, OIS)', 'camera_sensor_ultra': None, 'camera_sensor_telephoto': 'Sony IMX315 (12MP, f/2.8, 2x optical zoom)', 'battery_tech': 'Li-Ion (2691mAh, non-removable)', 'charging_watt': 15, 'display_type': 'Retina IPS LCD', 'refresh_rate_hz': 60},
    {'company_name': 'Apple', 'product_name': 'iPhone XR', 'batch_number': 'IMPORT-2018', 'category': 'Smartphone', 'processor_score': 360000, 'ram_gb': 3, 'storage_gb': 64, 'battery_mah': 2942, 'screen_inches': 6.1, 'camera_mp': 12.0, 'price_usd': 749, 'weight_g': 194, 'processor_model': 'Apple A12 Bionic (7nm, 6-core CPU, 4-core GPU)', 'ram_type': '3GB LPDDR4X', 'storage_type': '64GB/128GB/256GB NVMe', 'camera_sensor_main': 'Sony IMX363 (12MP, f/1.8, OIS)', 'camera_sensor_ultra': None, 'camera_sensor_telephoto': None, 'battery_tech': 'Li-Ion (2942mAh, non-removable)', 'charging_watt': 15, 'display_type': 'Liquid Retina IPS LCD', 'refresh_rate_hz': 60},
    {'company_name': 'Apple', 'product_name': 'iPhone XS', 'batch_number': 'IMPORT-2018', 'category': 'Smartphone', 'processor_score': 370000, 'ram_gb': 4, 'storage_gb': 64, 'battery_mah': 2658, 'screen_inches': 5.8, 'camera_mp': 12.0, 'price_usd': 999, 'weight_g': 177, 'processor_model': 'Apple A12 Bionic (7nm, 6-core CPU, 4-core GPU)', 'ram_type': '4GB LPDDR4X', 'storage_type': '64GB/256GB/512GB NVMe', 'camera_sensor_main': 'Sony IMX363 (12MP, f/1.8, OIS)', 'camera_sensor_ultra': None, 'camera_sensor_telephoto': 'Sony IMX363 (12MP, f/2.4, 2x optical zoom)', 'battery_tech': 'Li-Ion (2658mAh, non-removable)', 'charging_watt': 15, 'display_type': 'Super Retina OLED, HDR10, Dolby Vision', 'refresh_rate_hz': 60},
    {'company_name': 'Apple', 'product_name': 'iPhone XS Max', 'batch_number': 'IMPORT-2018', 'category': 'Smartphone', 'processor_score': 375000, 'ram_gb': 4, 'storage_gb': 64, 'battery_mah': 3174, 'screen_inches': 6.5, 'camera_mp': 12.0, 'price_usd': 1099, 'weight_g': 208, 'processor_model': 'Apple A12 Bionic (7nm, 6-core CPU, 4-core GPU)', 'ram_type': '4GB LPDDR4X', 'storage_type': '64GB/256GB/512GB NVMe', 'camera_sensor_main': 'Sony IMX363 (12MP, f/1.8, OIS)', 'camera_sensor_ultra': None, 'camera_sensor_telephoto': 'Sony IMX363 (12MP, f/2.4, 2x optical zoom)', 'battery_tech': 'Li-Ion (3174mAh, non-removable)', 'charging_watt': 15, 'display_type': 'Super Retina OLED, HDR10, Dolby Vision', 'refresh_rate_hz': 60},
    {'company_name': 'Apple', 'product_name': 'iPhone 11', 'batch_number': 'IMPORT-2019', 'category': 'Smartphone', 'processor_score': 460000, 'ram_gb': 4, 'storage_gb': 64, 'battery_mah': 3110, 'screen_inches': 6.1, 'camera_mp': 12.0, 'price_usd': 699, 'weight_g': 194, 'processor_model': 'Apple A13 Bionic (7nm+, 6-core CPU, 4-core GPU)', 'ram_type': '4GB LPDDR4X', 'storage_type': '64GB/128GB/256GB NVMe', 'camera_sensor_main': 'Sony IMX503 (12MP, f/1.8, OIS)', 'camera_sensor_ultra': 'Sony IMX516 (12MP, f/2.4, 120° FOV)', 'camera_sensor_telephoto': None, 'battery_tech': 'Li-Ion (3110mAh, non-removable)', 'charging_watt': 18, 'display_type': 'Liquid Retina IPS LCD', 'refresh_rate_hz': 60},
    {'company_name': 'Apple', 'product_name': 'iPhone 11 Pro', 'batch_number': 'IMPORT-2019', 'category': 'Smartphone', 'processor_score': 470000, 'ram_gb': 4, 'storage_gb': 64, 'battery_mah': 3046, 'screen_inches': 5.8, 'camera_mp': 12.0, 'price_usd': 999, 'weight_g': 188, 'processor_model': 'Apple A13 Bionic (7nm+, 6-core CPU, 4-core GPU)', 'ram_type': '4GB LPDDR4X', 'storage_type': '64GB/256GB/512GB NVMe', 'camera_sensor_main': 'Sony IMX503 (12MP, f/1.8, OIS)', 'camera_sensor_ultra': 'Sony IMX516 (12MP, f/2.4, 120° FOV)', 'camera_sensor_telephoto': 'Sony IMX503 (12MP, f/2.0, 2x optical zoom)', 'battery_tech': 'Li-Ion (3046mAh, non-removable)', 'charging_watt': 18, 'display_type': 'Super Retina XDR OLED, HDR10, Dolby Vision', 'refresh_rate_hz': 60},
    {'company_name': 'Apple', 'product_name': 'iPhone 11 Pro Max', 'batch_number': 'IMPORT-2019', 'category': 'Smartphone', 'processor_score': 480000, 'ram_gb': 4, 'storage_gb': 64, 'battery_mah': 3969, 'screen_inches': 6.5, 'camera_mp': 12.0, 'price_usd': 1099, 'weight_g': 226, 'processor_model': 'Apple A13 Bionic (7nm+, 6-core CPU, 4-core GPU)', 'ram_type': '4GB LPDDR4X', 'storage_type': '64GB/256GB/512GB NVMe', 'camera_sensor_main': 'Sony IMX503 (12MP, f/1.8, OIS)', 'camera_sensor_ultra': 'Sony IMX516 (12MP, f/2.4, 120° FOV)', 'camera_sensor_telephoto': 'Sony IMX503 (12MP, f/2.0, 2x optical zoom)', 'battery_tech': 'Li-Ion (3969mAh, non-removable)', 'charging_watt': 18, 'display_type': 'Super Retina XDR OLED, HDR10, Dolby Vision', 'refresh_rate_hz': 60},
    {'company_name': 'Apple', 'product_name': 'iPhone SE (2nd generation)', 'batch_number': 'IMPORT-2020', 'category': 'Smartphone', 'processor_score': 490000, 'ram_gb': 3, 'storage_gb': 64, 'battery_mah': 1821, 'screen_inches': 4.7, 'camera_mp': 12.0, 'price_usd': 399, 'weight_g': 148, 'processor_model': 'Apple A13 Bionic (7nm+, 6-core CPU, 4-core GPU)', 'ram_type': '3GB LPDDR4X', 'storage_type': '64GB/128GB/256GB NVMe', 'camera_sensor_main': 'Sony IMX315 (12MP, f/1.8, OIS)', 'camera_sensor_ultra': None, 'camera_sensor_telephoto': None, 'battery_tech': 'Li-Ion (1821mAh, non-removable)', 'charging_watt': 18, 'display_type': 'Retina IPS LCD', 'refresh_rate_hz': 60},
    {'company_name': 'Apple', 'product_name': 'iPhone 12 mini', 'batch_number': 'IMPORT-2020', 'category': 'Smartphone', 'processor_score': 620000, 'ram_gb': 4, 'storage_gb': 64, 'battery_mah': 2227, 'screen_inches': 5.4, 'camera_mp': 12.0, 'price_usd': 699, 'weight_g': 135, 'processor_model': 'Apple A14 Bionic (5nm, 6-core CPU, 4-core GPU)', 'ram_type': '4GB LPDDR4X', 'storage_type': '64GB/128GB/256GB NVMe', 'camera_sensor_main': 'Sony IMX503 (12MP, f/1.6, OIS)', 'camera_sensor_ultra': 'Sony IMX516 (12MP, f/2.4, 120° FOV)', 'camera_sensor_telephoto': None, 'battery_tech': 'Li-Ion (2227mAh, non-removable)', 'charging_watt': 20, 'display_type': 'Super Retina XDR OLED, HDR10, Dolby Vision', 'refresh_rate_hz': 60},
    {'company_name': 'Apple', 'product_name': 'iPhone 12', 'batch_number': 'IMPORT-2020', 'category': 'Smartphone', 'processor_score': 630000, 'ram_gb': 4, 'storage_gb': 64, 'battery_mah': 2815, 'screen_inches': 6.1, 'camera_mp': 12.0, 'price_usd': 799, 'weight_g': 164, 'processor_model': 'Apple A14 Bionic (5nm, 6-core CPU, 4-core GPU)', 'ram_type': '4GB LPDDR4X', 'storage_type': '64GB/128GB/256GB NVMe', 'camera_sensor_main': 'Sony IMX503 (12MP, f/1.6, OIS)', 'camera_sensor_ultra': 'Sony IMX516 (12MP, f/2.4, 120° FOV)', 'camera_sensor_telephoto': None, 'battery_tech': 'Li-Ion (2815mAh, non-removable)', 'charging_watt': 20, 'display_type': 'Super Retina XDR OLED, HDR10, Dolby Vision', 'refresh_rate_hz': 60},
    {'company_name': 'Apple', 'product_name': 'iPhone 12 Pro', 'batch_number': 'IMPORT-2020', 'category': 'Smartphone', 'processor_score': 640000, 'ram_gb': 6, 'storage_gb': 128, 'battery_mah': 2815, 'screen_inches': 6.1, 'camera_mp': 12.0, 'price_usd': 999, 'weight_g': 189, 'processor_model': 'Apple A14 Bionic (5nm, 6-core CPU, 4-core GPU)', 'ram_type': '6GB LPDDR4X', 'storage_type': '128GB/256GB/512GB NVMe', 'camera_sensor_main': 'Sony IMX503 (12MP, f/1.6, OIS)', 'camera_sensor_ultra': 'Sony IMX516 (12MP, f/2.4, 120° FOV)', 'camera_sensor_telephoto': 'Sony IMX503 (12MP, f/2.0, 2x optical zoom)', 'battery_tech': 'Li-Ion (2815mAh, non-removable)', 'charging_watt': 20, 'display_type': 'Super Retina XDR OLED, HDR10, Dolby Vision', 'refresh_rate_hz': 60},
    {'company_name': 'Apple', 'product_name': 'iPhone 12 Pro Max', 'batch_number': 'IMPORT-2020', 'category': 'Smartphone', 'processor_score': 650000, 'ram_gb': 6, 'storage_gb': 128, 'battery_mah': 3687, 'screen_inches': 6.7, 'camera_mp': 12.0, 'price_usd': 1099, 'weight_g': 228, 'processor_model': 'Apple A14 Bionic (5nm, 6-core CPU, 4-core GPU)', 'ram_type': '6GB LPDDR4X', 'storage_type': '128GB/256GB/512GB NVMe', 'camera_sensor_main': 'Sony IMX603 (12MP, f/1.6, Sensor-shift OIS)', 'camera_sensor_ultra': 'Sony IMX516 (12MP, f/2.4, 120° FOV)', 'camera_sensor_telephoto': 'Sony IMX603 (12MP, f/2.2, 2.5x optical zoom)', 'battery_tech': 'Li-Ion (3687mAh, non-removable)', 'charging_watt': 20, 'display_type': 'Super Retina XDR OLED, HDR10, Dolby Vision', 'refresh_rate_hz': 60},
    {'company_name': 'Apple', 'product_name': 'iPhone 13 mini', 'batch_number': 'IMPORT-2021', 'category': 'Smartphone', 'processor_score': 840000, 'ram_gb': 4, 'storage_gb': 128, 'battery_mah': 2406, 'screen_inches': 5.4, 'camera_mp': 12.0, 'price_usd': 699, 'weight_g': 140, 'processor_model': 'Apple A15 Bionic (5nm, 6-core CPU, 4-core GPU)', 'ram_type': '4GB LPDDR4X', 'storage_type': '128GB/256GB/512GB NVMe', 'camera_sensor_main': 'Sony IMX703 (12MP, f/1.6, Sensor-shift OIS)', 'camera_sensor_ultra': 'Sony IMX633 (12MP, f/1.8, 120° FOV)', 'camera_sensor_telephoto': None, 'battery_tech': 'Li-Ion (2406mAh, non-removable)', 'charging_watt': 20, 'display_type': 'Super Retina XDR OLED, HDR10, Dolby Vision', 'refresh_rate_hz': 60},
    {'company_name': 'Apple', 'product_name': 'iPhone 13', 'batch_number': 'IMPORT-2021', 'category': 'Smartphone', 'processor_score': 850000, 'ram_gb': 4, 'storage_gb': 128, 'battery_mah': 3227, 'screen_inches': 6.1, 'camera_mp': 12.0, 'price_usd': 799, 'weight_g': 174, 'processor_model': 'Apple A15 Bionic (5nm, 6-core CPU, 4-core GPU)', 'ram_type': '4GB LPDDR4X', 'storage_type': '128GB/256GB/512GB NVMe', 'camera_sensor_main': 'Sony IMX703 (12MP, f/1.6, Sensor-shift OIS)', 'camera_sensor_ultra': 'Sony IMX633 (12MP, f/1.8, 120° FOV)', 'camera_sensor_telephoto': None, 'battery_tech': 'Li-Ion (3227mAh, non-removable)', 'charging_watt': 20, 'display_type': 'Super Retina XDR OLED, HDR10, Dolby Vision', 'refresh_rate_hz': 60},
    {'company_name': 'Apple', 'product_name': 'iPhone 13 Pro', 'batch_number': 'IMPORT-2021', 'category': 'Smartphone', 'processor_score': 860000, 'ram_gb': 6, 'storage_gb': 128, 'battery_mah': 3095, 'screen_inches': 6.1, 'camera_mp': 12.0, 'price_usd': 999, 'weight_g': 204, 'processor_model': 'Apple A15 Bionic (5nm, 6-core CPU, 5-core GPU)', 'ram_type': '6GB LPDDR4X', 'storage_type': '128GB/256GB/512GB/1TB NVMe', 'camera_sensor_main': 'Sony IMX703 (12MP, f/1.6, Sensor-shift OIS)', 'camera_sensor_ultra': 'Sony IMX633 (12MP, f/1.8, 120° FOV, macro)', 'camera_sensor_telephoto': 'Sony IMX703 (12MP, f/2.8, 3x optical zoom)', 'battery_tech': 'Li-Ion (3095mAh, non-removable)', 'charging_watt': 20, 'display_type': 'Super Retina XDR LTPO OLED, HDR10, Dolby Vision', 'refresh_rate_hz': 120},
    {'company_name': 'Apple', 'product_name': 'iPhone 13 Pro Max', 'batch_number': 'IMPORT-2021', 'category': 'Smartphone', 'processor_score': 870000, 'ram_gb': 6, 'storage_gb': 128, 'battery_mah': 4352, 'screen_inches': 6.7, 'camera_mp': 12.0, 'price_usd': 1099, 'weight_g': 240, 'processor_model': 'Apple A15 Bionic (5nm, 6-core CPU, 5-core GPU)', 'ram_type': '6GB LPDDR4X', 'storage_type': '128GB/256GB/512GB/1TB NVMe', 'camera_sensor_main': 'Sony IMX703 (12MP, f/1.6, Sensor-shift OIS)', 'camera_sensor_ultra': 'Sony IMX633 (12MP, f/1.8, 120° FOV, macro)', 'camera_sensor_telephoto': 'Sony IMX703 (12MP, f/2.8, 3x optical zoom)', 'battery_tech': 'Li-Ion (4352mAh, non-removable)', 'charging_watt': 20, 'display_type': 'Super Retina XDR LTPO OLED, HDR10, Dolby Vision', 'refresh_rate_hz': 120},
    {'company_name': 'Apple', 'product_name': 'iPhone SE (3rd generation)', 'batch_number': 'IMPORT-2022', 'category': 'Smartphone', 'processor_score': 960000, 'ram_gb': 4, 'storage_gb': 64, 'battery_mah': 2018, 'screen_inches': 4.7, 'camera_mp': 12.0, 'price_usd': 429, 'weight_g': 144, 'processor_model': 'Apple A15 Bionic (5nm, 6-core CPU, 4-core GPU)', 'ram_type': '4GB LPDDR4X', 'storage_type': '64GB/128GB/256GB NVMe', 'camera_sensor_main': 'Sony IMX315 (12MP, f/1.8, OIS)', 'camera_sensor_ultra': None, 'camera_sensor_telephoto': None, 'battery_tech': 'Li-Ion (2018mAh, non-removable)', 'charging_watt': 20, 'display_type': 'Retina IPS LCD', 'refresh_rate_hz': 60},
    {'company_name': 'Apple', 'product_name': 'iPhone 14', 'batch_number': 'IMPORT-2022', 'category': 'Smartphone', 'processor_score': 960000, 'ram_gb': 6, 'storage_gb': 128, 'battery_mah': 3279, 'screen_inches': 6.1, 'camera_mp': 12.0, 'price_usd': 799, 'weight_g': 172, 'processor_model': 'Apple A15 Bionic (5nm, 6-core CPU, 5-core GPU)', 'ram_type': '6GB LPDDR4X', 'storage_type': '128GB/256GB/512GB NVMe', 'camera_sensor_main': 'Sony IMX703 (12MP, f/1.5, Sensor-shift OIS)', 'camera_sensor_ultra': 'Sony IMX633 (12MP, f/2.4, 120° FOV)', 'camera_sensor_telephoto': None, 'battery_tech': 'Li-Ion (3279mAh, non-removable)', 'charging_watt': 20, 'display_type': 'Super Retina XDR OLED, HDR10, Dolby Vision', 'refresh_rate_hz': 60},
    {'company_name': 'Apple', 'product_name': 'iPhone 14 Plus', 'batch_number': 'IMPORT-2022', 'category': 'Smartphone', 'processor_score': 970000, 'ram_gb': 6, 'storage_gb': 128, 'battery_mah': 4325, 'screen_inches': 6.7, 'camera_mp': 12.0, 'price_usd': 899, 'weight_g': 203, 'processor_model': 'Apple A15 Bionic (5nm, 6-core CPU, 5-core GPU)', 'ram_type': '6GB LPDDR4X', 'storage_type': '128GB/256GB/512GB NVMe', 'camera_sensor_main': 'Sony IMX703 (12MP, f/1.5, Sensor-shift OIS)', 'camera_sensor_ultra': 'Sony IMX633 (12MP, f/2.4, 120° FOV)', 'camera_sensor_telephoto': None, 'battery_tech': 'Li-Ion (4325mAh, non-removable)', 'charging_watt': 20, 'display_type': 'Super Retina XDR OLED, HDR10, Dolby Vision', 'refresh_rate_hz': 60},
    {'company_name': 'Apple', 'product_name': 'iPhone 14 Pro', 'batch_number': 'IMPORT-2022', 'category': 'Smartphone', 'processor_score': 1250000, 'ram_gb': 6, 'storage_gb': 128, 'battery_mah': 3200, 'screen_inches': 6.1, 'camera_mp': 48.0, 'price_usd': 999, 'weight_g': 206, 'processor_model': 'Apple A16 Bionic (4nm, 6-core CPU, 5-core GPU)', 'ram_type': '6GB LPDDR5', 'storage_type': '128GB/256GB/512GB/1TB NVMe', 'camera_sensor_main': 'Sony IMX803 (48MP, f/1.78, Sensor-shift OIS)', 'camera_sensor_ultra': 'Sony IMX633 (12MP, f/2.2, 120° FOV)', 'camera_sensor_telephoto': 'Sony IMX713 (12MP, f/2.8, 3x optical zoom)', 'battery_tech': 'Li-Ion (3200mAh, non-removable)', 'charging_watt': 27, 'display_type': 'Super Retina XDR LTPO OLED, HDR10, Dolby Vision', 'refresh_rate_hz': 120},
    {'company_name': 'Apple', 'product_name': 'iPhone 14 Pro Max', 'batch_number': 'IMPORT-2022', 'category': 'Smartphone', 'processor_score': 1270000, 'ram_gb': 6, 'storage_gb': 128, 'battery_mah': 4323, 'screen_inches': 6.7, 'camera_mp': 48.0, 'price_usd': 1099, 'weight_g': 240, 'processor_model': 'Apple A16 Bionic (4nm, 6-core CPU, 5-core GPU)', 'ram_type': '6GB LPDDR5', 'storage_type': '128GB/256GB/512GB/1TB NVMe', 'camera_sensor_main': 'Sony IMX803 (48MP, f/1.78, Sensor-shift OIS)', 'camera_sensor_ultra': 'Sony IMX633 (12MP, f/2.2, 120° FOV)', 'camera_sensor_telephoto': 'Sony IMX713 (12MP, f/2.8, 3x optical zoom)', 'battery_tech': 'Li-Ion (4323mAh, non-removable)', 'charging_watt': 27, 'display_type': 'Super Retina XDR LTPO OLED, HDR10, Dolby Vision', 'refresh_rate_hz': 120},
    {'company_name': 'Apple', 'product_name': 'iPhone 15', 'batch_number': 'IMPORT-2023', 'category': 'Smartphone', 'processor_score': 1350000, 'ram_gb': 6, 'storage_gb': 128, 'battery_mah': 3349, 'screen_inches': 6.1, 'camera_mp': 48.0, 'price_usd': 799, 'weight_g': 171, 'processor_model': 'Apple A16 Bionic (4nm, 6-core CPU, 5-core GPU)', 'ram_type': '6GB LPDDR5', 'storage_type': '128GB/256GB/512GB NVMe', 'camera_sensor_main': 'Sony IMX803 (48MP, f/1.6, Sensor-shift OIS)', 'camera_sensor_ultra': 'Sony IMX633 (12MP, f/2.4, 120° FOV)', 'camera_sensor_telephoto': None, 'battery_tech': 'Li-Ion (3349mAh, non-removable)', 'charging_watt': 27, 'display_type': 'Super Retina XDR OLED, HDR10, Dolby Vision', 'refresh_rate_hz': 60},
    {'company_name': 'Apple', 'product_name': 'iPhone 15 Plus', 'batch_number': 'IMPORT-2023', 'category': 'Smartphone', 'processor_score': 1360000, 'ram_gb': 6, 'storage_gb': 128, 'battery_mah': 4383, 'screen_inches': 6.7, 'camera_mp': 48.0, 'price_usd': 899, 'weight_g': 201, 'processor_model': 'Apple A16 Bionic (4nm, 6-core CPU, 5-core GPU)', 'ram_type': '6GB LPDDR5', 'storage_type': '128GB/256GB/512GB NVMe', 'camera_sensor_main': 'Sony IMX803 (48MP, f/1.6, Sensor-shift OIS)', 'camera_sensor_ultra': 'Sony IMX633 (12MP, f/2.4, 120° FOV)', 'camera_sensor_telephoto': None, 'battery_tech': 'Li-Ion (4383mAh, non-removable)', 'charging_watt': 27, 'display_type': 'Super Retina XDR OLED, HDR10, Dolby Vision', 'refresh_rate_hz': 60},
    {'company_name': 'Apple', 'product_name': 'iPhone 15 Pro', 'batch_number': 'IMPORT-2023', 'category': 'Smartphone', 'processor_score': 1580000, 'ram_gb': 8, 'storage_gb': 128, 'battery_mah': 3274, 'screen_inches': 6.1, 'camera_mp': 48.0, 'price_usd': 999, 'weight_g': 187, 'processor_model': 'Apple A17 Pro (3nm, 6-core CPU, 6-core GPU)', 'ram_type': '8GB LPDDR5', 'storage_type': '128GB/256GB/512GB/1TB NVMe', 'camera_sensor_main': 'Sony IMX803 (48MP, f/1.78, Sensor-shift OIS)', 'camera_sensor_ultra': 'Sony IMX633 (12MP, f/2.2, 120° FOV)', 'camera_sensor_telephoto': 'Sony IMX913 (12MP, f/2.8, 3x optical zoom)', 'battery_tech': 'Li-Ion (3274mAh, non-removable)', 'charging_watt': 27, 'display_type': 'Super Retina XDR LTPO OLED, HDR10, Dolby Vision', 'refresh_rate_hz': 120},
    {'company_name': 'Apple', 'product_name': 'iPhone 15 Pro Max', 'batch_number': 'IMPORT-2023', 'category': 'Smartphone', 'processor_score': 1693091, 'ram_gb': 8, 'storage_gb': 256, 'battery_mah': 4441, 'screen_inches': 6.7, 'camera_mp': 48.0, 'price_usd': 1199, 'weight_g': 221, 'processor_model': 'Apple A17 Pro (3nm, 6-core CPU, 6-core GPU)', 'ram_type': '8GB LPDDR5', 'storage_type': '256GB/512GB/1TB NVMe', 'camera_sensor_main': 'Sony IMX803 (48MP, f/1.78, Sensor-shift OIS)', 'camera_sensor_ultra': 'Sony IMX633 (12MP, f/2.2, 120° FOV)', 'camera_sensor_telephoto': 'Sony/Tetraprism (12MP, f/2.8, 5x optical zoom)', 'battery_tech': 'Li-Ion (4441mAh, non-removable)', 'charging_watt': 27, 'display_type': 'Super Retina XDR LTPO OLED, HDR10, Dolby Vision', 'refresh_rate_hz': 120},
    {'company_name': 'Apple', 'product_name': 'iPhone 16', 'batch_number': 'IMPORT-2024', 'category': 'Smartphone', 'processor_score': 1750000, 'ram_gb': 8, 'storage_gb': 128, 'battery_mah': 3561, 'screen_inches': 6.1, 'camera_mp': 48.0, 'price_usd': 799, 'weight_g': 173, 'processor_model': 'Apple A18 (3nm, 6-core CPU, 5-core GPU)', 'ram_type': '8GB LPDDR5', 'storage_type': '128GB/256GB/512GB NVMe', 'camera_sensor_main': 'Sony IMX904 (48MP, f/1.6, Sensor-shift OIS)', 'camera_sensor_ultra': 'Sony IMX633 (12MP, f/2.4, 120° FOV)', 'camera_sensor_telephoto': None, 'battery_tech': 'Li-Ion (3561mAh, non-removable)', 'charging_watt': 27, 'display_type': 'Super Retina XDR OLED, HDR10, Dolby Vision', 'refresh_rate_hz': 60},
    {'company_name': 'Apple', 'product_name': 'iPhone 16 Plus', 'batch_number': 'IMPORT-2024', 'category': 'Smartphone', 'processor_score': 1760000, 'ram_gb': 8, 'storage_gb': 128, 'battery_mah': 4674, 'screen_inches': 6.7, 'camera_mp': 48.0, 'price_usd': 899, 'weight_g': 206, 'processor_model': 'Apple A18 (3nm, 6-core CPU, 5-core GPU)', 'ram_type': '8GB LPDDR5', 'storage_type': '128GB/256GB/512GB NVMe', 'camera_sensor_main': 'Sony IMX904 (48MP, f/1.6, Sensor-shift OIS)', 'camera_sensor_ultra': 'Sony IMX633 (12MP, f/2.4, 120° FOV)', 'camera_sensor_telephoto': None, 'battery_tech': 'Li-Ion (4674mAh, non-removable)', 'charging_watt': 27, 'display_type': 'Super Retina XDR OLED, HDR10, Dolby Vision', 'refresh_rate_hz': 60},
    {'company_name': 'Apple', 'product_name': 'iPhone 16e', 'batch_number': 'IMPORT-2024', 'category': 'Smartphone', 'processor_score': 1650000, 'ram_gb': 6, 'storage_gb': 128, 'battery_mah': 3200, 'screen_inches': 6.1, 'camera_mp': 48.0, 'price_usd': 699, 'weight_g': 170, 'processor_model': 'Apple A17 (RUMORED/EXPECTED)', 'ram_type': '6GB LPDDR5', 'storage_type': '128GB/256GB NVMe', 'camera_sensor_main': 'Sony IMX803 (48MP, f/1.8, OIS)', 'camera_sensor_ultra': None, 'camera_sensor_telephoto': None, 'battery_tech': 'Li-Ion (3200mAh, non-removable)', 'charging_watt': 27, 'display_type': 'Super Retina XDR OLED', 'refresh_rate_hz': 60},
    {'company_name': 'Apple', 'product_name': 'iPhone 16 Pro', 'batch_number': 'IMPORT-2024', 'category': 'Smartphone', 'processor_score': 1950000, 'ram_gb': 8, 'storage_gb': 128, 'battery_mah': 3582, 'screen_inches': 6.3, 'camera_mp': 48.0, 'price_usd': 999, 'weight_g': 199, 'processor_model': 'Apple A18 Pro (3nm, 6-core CPU, 6-core GPU)', 'ram_type': '8GB LPDDR5', 'storage_type': '128GB/256GB/512GB/1TB NVMe', 'camera_sensor_main': 'Sony IMX904 (48MP, f/1.78, Sensor-shift OIS)', 'camera_sensor_ultra': 'Sony IMX633 (48MP, f/2.2, 120° FOV)', 'camera_sensor_telephoto': 'Sony IMX913 (12MP, f/2.8, 5x optical zoom)', 'battery_tech': 'Li-Ion (3582mAh, non-removable)', 'charging_watt': 27, 'display_type': 'Super Retina XDR LTPO OLED, HDR10, Dolby Vision', 'refresh_rate_hz': 120},
    {'company_name': 'Apple', 'product_name': 'iPhone 16 Pro Max', 'batch_number': 'IMPORT-2024', 'category': 'Smartphone', 'processor_score': 1980000, 'ram_gb': 8, 'storage_gb': 256, 'battery_mah': 4685, 'screen_inches': 6.9, 'camera_mp': 48.0, 'price_usd': 1199, 'weight_g': 227, 'processor_model': 'Apple A18 Pro (3nm, 6-core CPU, 6-core GPU)', 'ram_type': '8GB LPDDR5', 'storage_type': '256GB/512GB/1TB NVMe', 'camera_sensor_main': 'Sony IMX904 (48MP, f/1.78, Sensor-shift OIS)', 'camera_sensor_ultra': 'Sony IMX633 (48MP, f/2.2, 120° FOV)', 'camera_sensor_telephoto': 'Sony/Tetraprism (12MP, f/2.8, 5x optical zoom)', 'battery_tech': 'Li-Ion (4685mAh, non-removable)', 'charging_watt': 27, 'display_type': 'Super Retina XDR LTPO OLED, HDR10, Dolby Vision', 'refresh_rate_hz': 120},
    {'company_name': 'Apple', 'product_name': 'iPhone 17 Air', 'batch_number': 'IMPORT-2025', 'category': 'Smartphone', 'processor_score': 2100000, 'ram_gb': 8, 'storage_gb': 256, 'battery_mah': 3600, 'screen_inches': 6.6, 'camera_mp': 48.0, 'price_usd': 999, 'weight_g': 165, 'processor_model': 'Apple A19 (RUMORED/EXPECTED, 3nm)', 'ram_type': '8GB LPDDR5X', 'storage_type': '256GB/512GB NVMe', 'camera_sensor_main': 'Sony IMX9xx (48MP, f/1.7, Sensor-shift OIS)', 'camera_sensor_ultra': 'Ultrawide (12MP f/2.2, 120° FOV)', 'camera_sensor_telephoto': None, 'battery_tech': 'Li-Ion (3600mAh, non-removable)', 'charging_watt': 30, 'display_type': 'Super Retina XDR OLED', 'refresh_rate_hz': 120},
    {'company_name': 'Apple', 'product_name': 'iPhone 17', 'batch_number': 'IMPORT-2025', 'category': 'Smartphone', 'processor_score': 2150000, 'ram_gb': 8, 'storage_gb': 128, 'battery_mah': 3800, 'screen_inches': 6.3, 'camera_mp': 48.0, 'price_usd': 799, 'weight_g': 175, 'processor_model': 'Apple A19 (RUMORED/EXPECTED, 3nm)', 'ram_type': '8GB LPDDR5X', 'storage_type': '128GB/256GB/512GB NVMe', 'camera_sensor_main': 'Sony IMX9xx (48MP, f/1.7, Sensor-shift OIS)', 'camera_sensor_ultra': 'Ultrawide (12MP f/2.2, 120° FOV)', 'camera_sensor_telephoto': None, 'battery_tech': 'Li-Ion (3800mAh, non-removable)', 'charging_watt': 30, 'display_type': 'Super Retina XDR OLED', 'refresh_rate_hz': 120},
    {'company_name': 'Apple', 'product_name': 'iPhone 17 Pro', 'batch_number': 'IMPORT-2025', 'category': 'Smartphone', 'processor_score': 2350000, 'ram_gb': 12, 'storage_gb': 256, 'battery_mah': 4000, 'screen_inches': 6.3, 'camera_mp': 48.0, 'price_usd': 999, 'weight_g': 198, 'processor_model': 'Apple A19 Pro (RUMORED/EXPECTED, 3nm)', 'ram_type': '12GB LPDDR5X', 'storage_type': '256GB/512GB/1TB NVMe', 'camera_sensor_main': 'Sony IMX9xx (48MP, f/1.6, Sensor-shift OIS)', 'camera_sensor_ultra': 'Sony IMX8xx (48MP, f/2.2, 120° FOV)', 'camera_sensor_telephoto': 'Sony Tetraprism (12MP, f/2.8, 5x optical zoom)', 'battery_tech': 'Li-Ion (4000mAh, non-removable)', 'charging_watt': 35, 'display_type': 'Super Retina XDR LTPO OLED, HDR10, Dolby Vision', 'refresh_rate_hz': 120},
    {'company_name': 'Apple', 'product_name': 'iPhone 17 Pro Max', 'batch_number': 'IMPORT-2025', 'category': 'Smartphone', 'processor_score': 2400000, 'ram_gb': 12, 'storage_gb': 256, 'battery_mah': 4700, 'screen_inches': 6.9, 'camera_mp': 48.0, 'price_usd': 1199, 'weight_g': 230, 'processor_model': 'Apple A19 Pro (RUMORED/EXPECTED, 3nm)', 'ram_type': '12GB LPDDR5X', 'storage_type': '256GB/512GB/1TB NVMe', 'camera_sensor_main': 'Sony IMX9xx (48MP, f/1.6, Sensor-shift OIS)', 'camera_sensor_ultra': 'Sony IMX8xx (48MP, f/2.2, 120° FOV)', 'camera_sensor_telephoto': 'Sony Tetraprism (12MP, f/2.8, 5x optical zoom)', 'battery_tech': 'Li-Ion (4700mAh, non-removable)', 'charging_watt': 35, 'display_type': 'Super Retina XDR LTPO OLED, HDR10, Dolby Vision', 'refresh_rate_hz': 120},
    # Samsung Galaxy phones
    {'company_name': 'Samsung', 'product_name': 'Samsung Galaxy S21', 'batch_number': 'IMPORT-2021', 'category': 'Smartphone', 'processor_score': 820000, 'ram_gb': 8, 'storage_gb': 128, 'battery_mah': 4000, 'screen_inches': 6.2, 'camera_mp': 12.0, 'price_usd': 799, 'weight_g': 169, 'processor_model': 'Exynos 2100 / Snapdragon 888 (5nm)', 'ram_type': '8GB LPDDR5', 'storage_type': '128GB/256GB UFS 3.1', 'camera_sensor_main': 'Samsung ISOCELL 3LU (12MP, f/1.8, OIS)', 'camera_sensor_ultra': 'Sony IMX563 (12MP, f/2.2, 120° FOV)', 'camera_sensor_telephoto': 'Samsung ISOCELL 3M5 (64MP, f/2.0, 3x hybrid zoom)', 'battery_tech': 'Li-Ion (4000mAh, non-removable)', 'charging_watt': 25, 'display_type': 'Dynamic AMOLED 2X, HDR10+', 'refresh_rate_hz': 120},
    {'company_name': 'Samsung', 'product_name': 'Samsung Galaxy S21 Plus', 'batch_number': 'IMPORT-2021', 'category': 'Smartphone', 'processor_score': 830000, 'ram_gb': 8, 'storage_gb': 128, 'battery_mah': 4800, 'screen_inches': 6.7, 'camera_mp': 12.0, 'price_usd': 999, 'weight_g': 200, 'processor_model': 'Exynos 2100 / Snapdragon 888 (5nm)', 'ram_type': '8GB LPDDR5', 'storage_type': '128GB/256GB UFS 3.1', 'camera_sensor_main': 'Samsung ISOCELL 3LU (12MP, f/1.8, OIS)', 'camera_sensor_ultra': 'Sony IMX563 (12MP, f/2.2, 120° FOV)', 'camera_sensor_telephoto': 'Samsung ISOCELL 3M5 (64MP, f/2.0, 3x hybrid zoom)', 'battery_tech': 'Li-Ion (4800mAh, non-removable)', 'charging_watt': 25, 'display_type': 'Dynamic AMOLED 2X, HDR10+', 'refresh_rate_hz': 120},
    {'company_name': 'Samsung', 'product_name': 'Samsung Galaxy S21 Ultra', 'batch_number': 'IMPORT-2021', 'category': 'Smartphone', 'processor_score': 850000, 'ram_gb': 12, 'storage_gb': 128, 'battery_mah': 5000, 'screen_inches': 6.8, 'camera_mp': 108.0, 'price_usd': 1199, 'weight_g': 227, 'processor_model': 'Exynos 2100 / Snapdragon 888 (5nm)', 'ram_type': '12GB LPDDR5', 'storage_type': '128GB/256GB/512GB UFS 3.1', 'camera_sensor_main': 'Samsung ISOCELL HM3 (108MP, f/1.8, OIS)', 'camera_sensor_ultra': 'Sony IMX563 (12MP, f/2.2, 120° FOV)', 'camera_sensor_telephoto': 'Dual Telephoto (10MP 3x + 10MP 10x optical zoom)', 'battery_tech': 'Li-Ion (5000mAh, non-removable)', 'charging_watt': 25, 'display_type': 'Dynamic AMOLED 2X, HDR10+', 'refresh_rate_hz': 120},
    {'company_name': 'Samsung', 'product_name': 'Samsung Galaxy S22', 'batch_number': 'IMPORT-2022', 'category': 'Smartphone', 'processor_score': 960000, 'ram_gb': 8, 'storage_gb': 128, 'battery_mah': 3700, 'screen_inches': 6.1, 'camera_mp': 50.0, 'price_usd': 799, 'weight_g': 167, 'processor_model': 'Exynos 2200 / Snapdragon 8 Gen 1 (4nm)', 'ram_type': '8GB LPDDR5', 'storage_type': '128GB/256GB UFS 3.1', 'camera_sensor_main': 'Samsung ISOCELL GN5 (50MP, f/1.8, OIS)', 'camera_sensor_ultra': 'Sony IMX563 (12MP, f/2.2, 120° FOV)', 'camera_sensor_telephoto': 'Samsung ISOCELL 3M5 (10MP, f/2.4, 3x optical zoom)', 'battery_tech': 'Li-Ion (3700mAh, non-removable)', 'charging_watt': 25, 'display_type': 'Dynamic AMOLED 2X, HDR10+', 'refresh_rate_hz': 120},
    {'company_name': 'Samsung', 'product_name': 'Samsung Galaxy S22 Ultra', 'batch_number': 'IMPORT-2022', 'category': 'Smartphone', 'processor_score': 1000000, 'ram_gb': 12, 'storage_gb': 256, 'battery_mah': 5000, 'screen_inches': 6.8, 'camera_mp': 108.0, 'price_usd': 1199, 'weight_g': 228, 'processor_model': 'Exynos 2200 / Snapdragon 8 Gen 1 (4nm)', 'ram_type': '12GB LPDDR5', 'storage_type': '256GB/512GB/1TB UFS 3.1', 'camera_sensor_main': 'Samsung ISOCELL HM3 (108MP, f/1.8, OIS)', 'camera_sensor_ultra': 'Sony IMX563 (12MP, f/2.2, 120° FOV)', 'camera_sensor_telephoto': 'Dual Telephoto (10MP 3x + 10MP 10x optical zoom)', 'battery_tech': 'Li-Ion (5000mAh, non-removable)', 'charging_watt': 45, 'display_type': 'Dynamic AMOLED 2X, HDR10+', 'refresh_rate_hz': 120},
    {'company_name': 'Samsung', 'product_name': 'Samsung Galaxy S23', 'batch_number': 'IMPORT-2023', 'category': 'Smartphone', 'processor_score': 1480000, 'ram_gb': 8, 'storage_gb': 128, 'battery_mah': 3900, 'screen_inches': 6.1, 'camera_mp': 50.0, 'price_usd': 799, 'weight_g': 168, 'processor_model': 'Snapdragon 8 Gen 2 for Galaxy (4nm)', 'ram_type': '8GB LPDDR5X', 'storage_type': '128GB/256GB UFS 4.0', 'camera_sensor_main': 'Samsung ISOCELL GN3 (50MP, f/1.8, OIS)', 'camera_sensor_ultra': 'Sony IMX564 (12MP, f/2.2, 120° FOV)', 'camera_sensor_telephoto': 'Samsung ISOCELL 3M5 (10MP, f/2.4, 3x optical zoom)', 'battery_tech': 'Li-Ion (3900mAh, non-removable)', 'charging_watt': 25, 'display_type': 'Dynamic AMOLED 2X, HDR10+', 'refresh_rate_hz': 120},
    {'company_name': 'Samsung', 'product_name': 'Samsung Galaxy S23 Ultra', 'batch_number': 'IMPORT-2023', 'category': 'Smartphone', 'processor_score': 1600000, 'ram_gb': 12, 'storage_gb': 256, 'battery_mah': 5000, 'screen_inches': 6.8, 'camera_mp': 200.0, 'price_usd': 1199, 'weight_g': 234, 'processor_model': 'Snapdragon 8 Gen 2 for Galaxy (4nm)', 'ram_type': '12GB LPDDR5X', 'storage_type': '256GB/512GB/1TB UFS 4.0', 'camera_sensor_main': 'Samsung ISOCELL HP2 (200MP, f/1.7, OIS)', 'camera_sensor_ultra': 'Sony IMX564 (12MP, f/2.2, 120° FOV)', 'camera_sensor_telephoto': 'Dual Telephoto (10MP 3x + 10MP 10x optical zoom)', 'battery_tech': 'Li-Ion (5000mAh, non-removable)', 'charging_watt': 45, 'display_type': 'Dynamic AMOLED 2X, HDR10+', 'refresh_rate_hz': 120},
    {'company_name': 'Samsung', 'product_name': 'Samsung Galaxy S24 Ultra', 'batch_number': 'IMPORT-2024', 'category': 'Smartphone', 'processor_score': 1820000, 'ram_gb': 12, 'storage_gb': 256, 'battery_mah': 5000, 'screen_inches': 6.8, 'camera_mp': 200.0, 'price_usd': 1299, 'weight_g': 233, 'processor_model': 'Snapdragon 8 Gen 3 for Galaxy (4nm)', 'ram_type': '12GB LPDDR5X', 'storage_type': '256GB/512GB/1TB UFS 4.0', 'camera_sensor_main': 'Samsung ISOCELL HP2SX (200MP, f/1.7, OIS)', 'camera_sensor_ultra': 'Sony IMX564 (12MP, f/2.2, 120° FOV)', 'camera_sensor_telephoto': 'Dual Telephoto (10MP 3x + 50MP 5x optical zoom)', 'battery_tech': 'Li-Ion (5000mAh, non-removable)', 'charging_watt': 45, 'display_type': 'Dynamic AMOLED 2X, HDR10+', 'refresh_rate_hz': 120},
    # Realme phones
    {'company_name': 'Realme', 'product_name': 'Realme GT Neo 2', 'batch_number': 'IMPORT-2021', 'category': 'Smartphone', 'processor_score': 760000, 'ram_gb': 8, 'storage_gb': 128, 'battery_mah': 5000, 'screen_inches': 6.62, 'camera_mp': 64.0, 'price_usd': 450, 'weight_g': 199, 'processor_model': 'Qualcomm Snapdragon 870 (7nm, Octa-core)', 'ram_type': '8GB LPDDR5', 'storage_type': '128GB/256GB UFS 3.1', 'camera_sensor_main': 'Sony IMX682 (64MP, f/1.8)', 'camera_sensor_ultra': 'Ultrawide (8MP, f/2.3, 119° FOV)', 'camera_sensor_telephoto': None, 'battery_tech': 'Li-Po (5000mAh, non-removable)', 'charging_watt': 65, 'display_type': 'AMOLED, HDR10+', 'refresh_rate_hz': 120},
    {'company_name': 'Realme', 'product_name': 'Realme GT Neo 3T', 'batch_number': 'IMPORT-2022', 'category': 'Smartphone', 'processor_score': 820000, 'ram_gb': 8, 'storage_gb': 128, 'battery_mah': 5000, 'screen_inches': 6.62, 'camera_mp': 64.0, 'price_usd': 470, 'weight_g': 194, 'processor_model': 'Qualcomm Snapdragon 870 (7nm, Octa-core)', 'ram_type': '8GB LPDDR5', 'storage_type': '128GB/256GB UFS 3.1', 'camera_sensor_main': 'OmniVision OV64B (64MP, f/1.8)', 'camera_sensor_ultra': 'Ultrawide (8MP, f/2.3, 119° FOV)', 'camera_sensor_telephoto': None, 'battery_tech': 'Li-Po (5000mAh, non-removable)', 'charging_watt': 80, 'display_type': 'AMOLED, HDR10+', 'refresh_rate_hz': 120},
    {'company_name': 'Realme', 'product_name': 'Realme GT Neo 3', 'batch_number': 'IMPORT-2022', 'category': 'Smartphone', 'processor_score': 820000, 'ram_gb': 8, 'storage_gb': 128, 'battery_mah': 5000, 'screen_inches': 6.7, 'camera_mp': 50.0, 'price_usd': 600, 'weight_g': 188, 'processor_model': 'MediaTek Dimensity 8100 (5nm, Octa-core)', 'ram_type': '8GB LPDDR5', 'storage_type': '128GB/256GB UFS 3.1', 'camera_sensor_main': 'Sony IMX766 (50MP, f/1.9, OIS)', 'camera_sensor_ultra': 'Ultrawide (8MP, f/2.3, 119° FOV)', 'camera_sensor_telephoto': None, 'battery_tech': 'Li-Po (5000mAh, non-removable)', 'charging_watt': 80, 'display_type': 'AMOLED, HDR10+', 'refresh_rate_hz': 120},
    {'company_name': 'Realme', 'product_name': 'Realme GT 5', 'batch_number': 'IMPORT-2023', 'category': 'Smartphone', 'processor_score': 1540000, 'ram_gb': 12, 'storage_gb': 256, 'battery_mah': 5240, 'screen_inches': 6.74, 'camera_mp': 50.0, 'price_usd': 720, 'weight_g': 205, 'processor_model': 'Qualcomm Snapdragon 8 Gen 2 (4nm, Octa-core)', 'ram_type': '12GB LPDDR5X', 'storage_type': '256GB/512GB UFS 4.0', 'camera_sensor_main': 'Sony IMX890 (50MP, f/1.9, OIS)', 'camera_sensor_ultra': 'Ultrawide (8MP, f/2.2, 112° FOV)', 'camera_sensor_telephoto': None, 'battery_tech': 'Li-Po (5240mAh, non-removable)', 'charging_watt': 240, 'display_type': 'AMOLED, HDR10+', 'refresh_rate_hz': 144},
]

# Default admin/producer/verifier accounts
SEED_USERS = [
    {'username': 'apple_producer', 'password': 'apple123', 'role': 'producer', 'company_name': 'Apple'},
    {'username': 'samsung_producer', 'password': 'samsung123', 'role': 'producer', 'company_name': 'Samsung'},
    {'username': 'realme_producer', 'password': 'realme123', 'role': 'producer', 'company_name': 'Realme'},
    {'username': 'consumer1', 'password': 'consumer123', 'role': 'consumer', 'company_name': None},
    {'username': 'verifier1', 'password': 'verifier123', 'role': 'verifier', 'company_name': None},
]
